version: '2.0'
services:
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data

  backend:
    build: 
      context: ./backend

    environment:
      PORT: 3000
    depends_on:
      - redis
    ports:
      - '3000:3000'

volumes:
  cache:
    driver: local