version: '2.0'
services:
  redis:
    image: redis/redis-stack:latest
    restart: always
    ports:
      - '6379:6379'
    volumes: 
      - cache:/data

  backend:
    build: 
      context: ./backend

    environment:
      PORT: 3000
    depends_on:
      - redis
    ports:
      - '3000:3000'

volumes:
  cache:
    driver: local